/* SPDX-License-Identifier: MIT */
/* Generated by gen_fwif.py from the Linux drm/imagination FWIF headers. */
#ifndef OPENFW_FWIF_H
#define OPENFW_FWIF_H

/* struct rogue_fwif_sysinit: 544 bytes */
#define SIZEOF_SYSINIT 544
#define OFF_SYSINIT_FIRMWARE_STARTED 352
#define OFF_SYSINIT_FAULT_PHYS_ADDR 0
#define OFF_SYSINIT_FW_SYS_DATA_FW_ADDR 324
#define OFF_SYSINIT_RUNTIME_CFG_FW_ADDR 316
#define OFF_SYSINIT_TRACE_BUF_CTL_FW_ADDR 320
#define OFF_SYSINIT_INITIAL_CORE_CLOCK_SPEED 344

/* struct rogue_fwif_osinit: 104 bytes */
#define SIZEOF_OSINIT 104
#define OFF_OSINIT_KERNEL_CCBCTL_FW_ADDR 0
#define OFF_OSINIT_KERNEL_CCB_FW_ADDR 4
#define OFF_OSINIT_KERNEL_CCB_RTN_SLOTS_FW_ADDR 8
#define OFF_OSINIT_FIRMWARE_CCBCTL_FW_ADDR 12
#define OFF_OSINIT_FIRMWARE_CCB_FW_ADDR 16
#define OFF_OSINIT_FW_OS_DATA_FW_ADDR 36

/* struct rogue_fwif_osdata: 584 bytes */
#define SIZEOF_OSDATA 584
#define OFF_OSDATA_POWER_SYNC_FW_ADDR 572
#define OFF_OSDATA_KCCB_CMDS_EXECUTED 568
#define OFF_OSDATA_FW_OS_CONFIG_FLAGS 0

/* struct rogue_fwif_sysdata: 3624 bytes */
#define SIZEOF_SYSDATA 3624
#define OFF_SYSDATA_CONFIG_FLAGS 0
#define OFF_SYSDATA_POW_STATE 8

/* struct rogue_fwif_ccb_ctl: 144 bytes */
#define SIZEOF_CCB_CTL 144
#define OFF_CCB_CTL_WRITE_OFFSET 0
#define OFF_CCB_CTL_READ_OFFSET 128
#define OFF_CCB_CTL_WRAP_MASK 132
#define OFF_CCB_CTL_CMD_SIZE 136

/* struct rogue_fwif_kccb_cmd: 88 bytes */
#define SIZEOF_KCCB_CMD 88
#define OFF_KCCB_CMD_CMD_TYPE 0
#define OFF_KCCB_CMD_KCCB_FLAGS 4
#define OFF_KCCB_CMD_CMD_DATA 8
#define OFF_KCCB_CMD_CMD_DATA_POW_DATA_POW_TYPE 8
#define OFF_KCCB_CMD_CMD_DATA_POW_DATA_POWER_REQ_DATA_NUM_OF_DUSTS 12
#define OFF_KCCB_CMD_CMD_DATA_POW_DATA_POWER_REQ_DATA_FORCED 12
#define OFF_KCCB_CMD_CMD_DATA_POW_DATA_POWER_REQ_DATA_POW_REQUEST_TYPE 12
#define OFF_KCCB_CMD_CMD_DATA_MMU_CACHE_DATA_CACHE_FLAGS 8
#define OFF_KCCB_CMD_CMD_DATA_MMU_CACHE_DATA_MMU_CACHE_SYNC_FW_ADDR 12
#define OFF_KCCB_CMD_CMD_DATA_MMU_CACHE_DATA_MMU_CACHE_SYNC_UPDATE_VALUE 16

/* struct rogue_fwif_connection_ctl: 16 bytes */
#define SIZEOF_CONNECTION_CTL 16
#define OFF_CONNECTION_CTL_CONNECTION_FW_STATE 0
#define OFF_CONNECTION_CTL_CONNECTION_OS_STATE 4
#define OFF_CONNECTION_CTL_ALIVE_FW_TOKEN 8

/* struct rogue_fwif_tracebuf: 864 bytes */
#define SIZEOF_TRACEBUF 864
#define OFF_TRACEBUF_LOG_TYPE 0
#define OFF_TRACEBUF_TRACEBUF_SIZE_IN_DWORDS 856
#define OFF_TRACEBUF_TRACEBUF0_TRACE_POINTER 8
#define OFF_TRACEBUF_TRACEBUF0_TRACE_BUFFER_FW_ADDR 12

/* struct rogue_mipsfw_boot_data: 64 bytes */
#define SIZEOF_MIPSFW_BOOT_DATA 64
#define OFF_MIPSFW_BOOT_DATA_STACK_PHYS_ADDR 0
#define OFF_MIPSFW_BOOT_DATA_REG_BASE 8
#define OFF_MIPSFW_BOOT_DATA_PT_PHYS_ADDR 16
#define OFF_MIPSFW_BOOT_DATA_PT_LOG2_PAGE_SIZE 48
#define OFF_MIPSFW_BOOT_DATA_PT_NUM_PAGES 52

#define SF_OPENFW_BOOT 0x700210b0U /* "Initialised Firmware with config flags 0x%08x and extended config flags 0x%08x" */
#define SF_OPENFW_OS_INIT 0x70021092U /* "Initialised OS %d with config flags 0x%08x" */
#define SF_OPENFW_CLOCK 0x7001105dU /* "Core clock set to %d Hz" */
#define SF_OPENFW_GPU_INIT 0x70001044U /* "GPU init" */
#define SF_OPENFW_GPU_DEINIT 0x70001090U /* "GPU deinit" */
#define SF_OPENFW_KCCB 0x70037013U /* "KCCB Slot %u: Cmd=0x%08x, OSid=%u" */
#define SF_OPENFW_KCCB_RTN 0x70027011U /* "KCCB Slot %u: Return value %u" */
#define SF_OPENFW_KCCB_UNKNOWN 0x700710aaU /* "Unknown KCCB Command: KCCBCtl=0x%08x, KCCB=0x%08x, Roff=%u, Woff=%u, Wrap=%u, Cmd=0x%08x, CmdType=0x%08x" */
#define SF_OPENFW_BG 0x70017012U /* "Bg Task OSid = %u" */
#define SF_OPENFW_IRQ 0x70017014U /* "Irq Task (EVENT_STATUS=0x%08x)" */
#define SF_OPENFW_POW_IDLE 0x7001a013U /* "OS requested forced IDLE, pow flags: 0x%x" */
#define SF_OPENFW_POW_CANCEL_IDLE 0x7001a014U /* "OS cancelled forced IDLE, pow flags: 0x%x" */
#define SF_OPENFW_POW_OFF 0x7002a03bU /* "OS requested pow off (forced = %d), pow flags: 0x%x" */
#define SF_OPENFW_POW_DUSTS 0x7002a009U /* "Changing number of dusts from %d to %d" */
#define SF_OPENFW_PAGE_FAULT 0x7003b042U /* "Mips page fault detected (BadVAddr: 0x%08x, EntryLo0: 0x%08x, EntryLo1: 0x%08x)" */
#define SF_OPENFW_DBG_HEX4 0x7004f005U /* "0x%08x 0x%08x 0x%08x 0x%08x" */

#endif
